# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"export_notebooks": "00_core.ipynb",
         "ValueType": "01_data_types.ipynb",
         "IntType": "01_data_types.ipynb",
         "StringType": "01_data_types.ipynb",
         "ValueContainer": "01_data_types.ipynb",
         "get_auto_module_id": "02_modules_core.ipynb",
         "ModuleState": "02_modules_core.ipynb",
         "DharpaModule": "02_modules_core.ipynb",
         "EmptyObject": "02_modules_core.ipynb",
         "log": "99_utils.ipynb",
         "find_all_module_classes": "02_modules_core.ipynb",
         "DataSource": "03_data_sources.ipynb",
         "WidgetSource": "03_data_sources.ipynb",
         "InputFilesWidget": "03_data_sources.ipynb",
         "DataTarget": "03_data_targets.ipynb",
         "WidgetTarget": "03_data_targets.ipynb",
         "FileContentWidget": "03_data_targets.ipynb",
         "ValueLocationType": "05_workflows.ipynb",
         "ValueLocation": "05_workflows.ipynb",
         "DharpaWorkflow": "05_workflows.ipynb",
         "DharpaFile": "10_modules_files.ipynb",
         "DharpaFiles": "10_modules_files.ipynb",
         "FileSetValue": "10_modules_files.ipynb",
         "FilesCollectionModule": "10_modules_files.ipynb",
         "TextCorpus": "10_modules_files.ipynb",
         "TextCorpusValue": "10_modules_text.ipynb",
         "CorpusFromFiles": "10_modules_files.ipynb",
         "TextPreprocessSettingsModule": "10_modules_text.ipynb",
         "TextPreprocessingModule": "10_modules_text.ipynb",
         "TextCorpusInputValue": "10_modules_text.ipynb",
         "TokenizeTextModule": "10_modules_text.ipynb",
         "TextCorpusProcessingModule": "10_modules_text.ipynb",
         "LowercaseTextModule": "10_modules_text.ipynb",
         "RemoveStopwordsModule": "10_modules_text.ipynb",
         "CorpusProcessingWorkflow": "10_modules_text.ipynb",
         "load_modules": "99_utils.ipynb",
         "get_all_subclasses": "99_utils.ipynb",
         "get_subclass_map": "99_utils.ipynb",
         "get_snake_case_from_class": "99_utils.ipynb",
         "to_camel_case": "99_utils.ipynb",
         "get_module_name_from_class": "99_utils.ipynb",
         "graph_to_image": "99_utils.ipynb"}

modules = ["core.py",
           "data_types/core.py",
           "modules/core.py",
           "sources/core.py",
           "targets/core.py",
           "workflows.py",
           "modules/files.py",
           "modules/text.py",
           "utils.py"]

doc_url = "https://DHARPA-Project.github.io/dharpa_toolbox/"

git_url = "https://github.com/DHARPA-Project/dharpa_toolbox/tree/master/"

def custom_doc_links(name): return None
