# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/00_core.ipynb (unless otherwise specified).

__all__ = ['export_notebooks']

# Cell
def export_notebooks():

    import os
    import dharpa_toolbox as dt
    project_root = os.path.dirname(dt.__file__)
    os.chdir(project_root)
    from nbdev.export import notebook2script; notebook2script()

