# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'export_notebooks']

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'


def export_notebooks():

    import os
    import dharpa_toolbox as dt
    project_root = os.path.dirname(dt.__file__)
    os.chdir(project_root)
    from nbdev.export import notebook2script; notebook2script()

