# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/02_workflows.ipynb (unless otherwise specified).

__all__ = ['DharpaWorkflow']

# Cell
from typing import Optional
from traitlets import HasTraits, List, Dict
from .modules import DharpaModule

# default_exp workflows

#export
class DharpaWorkflow(HasTraits):

    modules = List()

    def add_module(self, module: DharpaModule):
        self.modules.append(module)

    def get_module(self, module_id: str) -> Optional[DharpaModule]:

        return self.modules.get(module_id, None)


    def __repr__(self) -> str:
        return f"DharpaWorkflow(modules={self.modules})"



